import assert from 'node:assert/strict';
import fs from 'node:fs';
import {runtime,root} from './overcast_test_runtime.mjs';
const R=runtime(),E=R.OvercastEngine;
let checks=0;function test(name,fn){fn();checks++;console.log('PASS '+name);}
const q=(t,cloudy,current=30)=>({t,baseline:30,current,ghi:300,dhi:cloudy?300:30,valid:true,
  evaluate:a=>({total:a===0?(cloudy?120:70):100}),admissible:()=>true,
  candidates:[{theta:0,total:cloudy?120:70,safe:true},{theta:30,total:100,safe:true}]});
test('confirmation counts elapsed minutes, not samples; a short cloud is rejected',()=>{const c=E.supervisor({confirmMin:10,dwellMin:20});for(let t=0;t<10;t++)assert.equal(c.step(q(t,true)).flag,false);assert.equal(c.step(q(10,false)).flag,false);assert.equal(c.step(q(11,true)).flag,false);assert.equal(c.step(q(21,true)).flag,true);});
test('exit and dwell affect the emitted angle, not only the mode label',()=>{const c=E.supervisor({confirmMin:5,dwellMin:20});c.step(q(0,true));assert.equal(c.step(q(5,true)).theta,0);assert.equal(c.step(q(6,false,0)).theta,0);assert.equal(c.step(q(12,false,0)).theta,0);assert.equal(c.step(q(25,false,0)).theta,30);});
test('a shadow constraint alone rejects an otherwise profitable angle',()=>{const c=E.supervisor({confirmMin:0});const a=q(0,true);a.candidates[0].safe=false;assert.equal(c.step(a).theta,30);assert.equal(E.supervisor({confirmMin:0}).step(q(0,true)).theta,0);});
test('invalid input alone forces baseline and resets confirmation',()=>{const c=E.supervisor({confirmMin:0});assert.equal(c.step(q(0,true)).theta,0);const a=q(1,true,0);a.valid=false;const b=c.step(a);assert.equal(b.theta,30);assert.equal(b.reason,'INVALID_WEATHER');});
test('near-optimal bands never span an unsafe interval',()=>{const c=E.curve({min:-2,max:2,step:.1,baseline:-2,current:-2,evaluate:()=>({total:10}),admissible:x=>Math.abs(x)>.5,nearOptimalW:1});assert.equal(c.nearBands.length,2);assert.ok(c.nearBands[0][1]<-.5&&c.nearBands[1][0]>.5);});
test('finite-vector and scalar callers execute the same supervisor',()=>{const a=q(0,true);const scalar=E.supervisor({confirmMin:0}).step(a);const vector=E.supervisor({confirmMin:0}).step({...a,baseline:[30,30],current:[30,30],evaluate:t=>a.evaluate(t[0]),candidates:a.candidates.map(p=>({...p,theta:[p.theta,p.theta]}))});assert.deepEqual(vector.theta,[scalar.theta,scalar.theta]);});
const cfg={lat:41.5763,lon:-.7981,dateStr:'2026-06-21',tz:2,altM:300,TL:3,dtMin:15,albedo:.2,axisAz:0,maxAngle:55,gcr:.397,cc:new Array(288).fill(0)};
const day=R.buildDay(cfg),fine=R.buildDay({...cfg,dtMin:1}),loop={deadbandDeg:1,slewDegS:.17,maxAngle:55},mp={modelo:'ajuste',slewDegS:.17};
test('annual and daily evaluator use the same actuator and BT guards; negative control differs',()=>{const a=R.evaluatePolicyDay('pvlib',day,fine,R.DCFG_DEFAULT,loop,mp),thN=R.thetaBaselineDay(day),thNF=R.thetaBaselineDay(fine);const guarded=R.execOnFineGrid(thN,15,fine.n,1,loop,thNF,fine),unguarded=R.execOnFineGrid(thN,15,fine.n,1,loop);assert.deepEqual(a.execF,guarded);assert.ok(unguarded.some((x,i)=>Math.abs(x-guarded[i])>1));const met=R.engineeringMetrics(fine,a,thNF,loop);assert.ok(Math.abs(met.poaWh-a.met.poaWh)>1);});
test('weather holes remain identifiable; no two-hour-plus interpolation or singleton crash',()=>{assert.equal(R.omInterp({tms:[0],ghi:[1],dni:[0],dhi:[1],cc:[1]},0),null);assert.equal(R.omInterp({tms:[0,10800000],ghi:[1,1],dni:[0,0],dhi:[1,1],cc:[1,1]},1),null);const d=R.buildDay({...cfg,om:{tms:[0,1],ghi:[1,1],dni:[0,0],dhi:[1,1],cc:[1,1]}});assert.ok(d.quality.every(x=>x.source==='missing'&&!x.valid));});
test('BT correction cannot exceed physical slew in the February regression case',()=>{const c={...cfg,dateStr:'2026-02-25'},d=R.buildDay(c),f=R.buildDay({...c,dtMin:1}),r=R.evaluatePolicyDay('pvlib',d,f,R.DCFG_DEFAULT,loop,mp),m=R.engineeringMetrics(f,r,R.thetaBaselineDay(f),loop);assert.ok(m.maxSlew<=.17+1e-9);assert.equal(m.shadowMinutes,0);assert.equal(m.violations,0);});
test('adaptive prefix is unchanged when future cloud data is changed',()=>{const a=R.buildDay({...cfg,cc:new Array(288).fill(1)}),b=R.buildDay({...cfg,cc:Array.from({length:288},(_,i)=>i<144?1:0)}),baseline=R.thetaBaselineDay(a),d={...R.DCFG_DEFAULT,adaptive:{confirmMin:15}};const ar=R.polAdaptive(a,baseline,[],d),br=R.polAdaptive(b,baseline,[],d);assert.deepEqual(ar.theta.slice(0,48),br.theta.slice(0,48));assert.deepEqual(ar.decisions.slice(0,48),br.decisions.slice(0,48));});
test('chronological holdout has no shared days; motor cap alone excludes highest-energy training candidate',()=>{const days=Array.from({length:10},(_,i)=>({date:'2026-01-'+String(i+1).padStart(2,'0')})),s=E.chronologicalSplit(days);assert.equal(s.train.length,7);assert.ok(s.train.at(-1).date<s.validation[0].date);const row={date:'2026-01-01',baselineWh:100,baselineMotorWh:1,moves:2,violations:0};const runs=[{id:'high',records:[{...row,poaWh:120,motorWh:10}]},{id:'low',records:[{...row,poaWh:110,motorWh:2}]}];assert.equal(E.selectConfiguration(runs).id,'high');assert.equal(E.selectConfiguration(runs,{motorBudgetWh:5}).id,'low');assert.throws(()=>E.chronologicalSplit([...days,days[0]]),/duplicadas/);});
test('P1 v2 uses the shared supervisor and a safe reachable candidate under slew',()=>{const pkg={schema:'overcast_p1_candidates_v2',objective:'front_effective_poa_shadow_safe',provenance:{},timestamp:['2026-01-01T00:00:00Z','2026-01-01T00:01:00Z'],steps:[{timestamp:'2026-01-01T00:00:00Z',baseline_candidate:0,ghi:300,dhi:280,valid:true,candidates:[{theta_by_asset_deg:[30,30],poa_front_effective_w_m2:100,admissible:true},{theta_by_asset_deg:[0,0],poa_front_effective_w_m2:120,admissible:true}]},{timestamp:'2026-01-01T00:01:00Z',baseline_candidate:0,ghi:300,dhi:20,valid:true,candidates:[{theta_by_asset_deg:[30,30],poa_front_effective_w_m2:100,admissible:true},{theta_by_asset_deg:[10,10],poa_front_effective_w_m2:90,admissible:true},{theta_by_asset_deg:[0,0],poa_front_effective_w_m2:130,admissible:false}]}]};const r=E.runCandidateSurface(pkg,{confirmMin:0,dwellMin:0,slewDegS:.17});assert.deepEqual(r.decisions[0].theta,[0,0]);assert.deepEqual(r.decisions[1].theta,[10,10]);assert.equal(r.decisions[1].reason,'SLEW_CANDIDATE');assert.equal(r.decisions[1].candidate.admissible,true);});
test('hard CONTROL overrides P1 candidates, keeps its explicit off-grid target and resets adaptive memory',()=>{const pkg={schema:'overcast_p1_candidates_v2',objective:'front_effective_poa_shadow_safe',provenance:{},timestamp:['2026-01-01T00:00:00Z','2026-01-01T00:01:00Z','2026-01-01T00:02:00Z'],steps:[{timestamp:'2026-01-01T00:00:00Z',baseline_candidate:0,ghi:300,dhi:300,valid:true,cloud_cover_fraction:.8,candidates:[{theta_by_asset_deg:[30],poa_front_effective_w_m2:100,admissible:true},{theta_by_asset_deg:[0],poa_front_effective_w_m2:120,admissible:true}]},{timestamp:'2026-01-01T00:01:00Z',baseline_candidate:0,ghi:300,dhi:300,valid:true,cloud_cover_fraction:.9,control:{locked:true,constraint_source:'wind_critical',target_by_asset_deg:[55]},candidates:[{theta_by_asset_deg:[30],poa_front_effective_w_m2:100,admissible:true},{theta_by_asset_deg:[0],poa_front_effective_w_m2:120,admissible:true}]},{timestamp:'2026-01-01T00:02:00Z',baseline_candidate:0,ghi:300,dhi:300,valid:true,cloud_cover_fraction:.7,candidates:[{theta_by_asset_deg:[30],poa_front_effective_w_m2:100,admissible:true},{theta_by_asset_deg:[0],poa_front_effective_w_m2:120,admissible:true}]}]};const r=E.runCandidateSurface(pkg,{confirmMin:1,dwellMin:0,slewDegS:1});assert.equal(r.decisions[1].reason,'HARD_CONSTRAINT');assert.equal(r.decisions[1].constraintSource,'wind_critical');assert.deepEqual(r.decisions[1].theta,[55]);assert.equal(r.decisions[1].candidate,null);assert.equal(r.decisions[1].physicsScored,false);assert.ok(Math.abs(r.decisions[1].cloudDelta-.1)<1e-12);assert.equal(r.decisions[2].flag,false);assert.equal(r.decisions[2].reason,'WAIT_CONFIRM');});
test('hard CONTROL step without explicit target is rejected instead of snapping to P1 grid',()=>{const pkg={schema:'overcast_p1_candidates_v2',objective:'front_effective_poa_shadow_safe',provenance:{},timestamp:['2026-01-01T00:00:00Z'],steps:[{timestamp:'2026-01-01T00:00:00Z',baseline_candidate:0,ghi:300,dhi:300,valid:true,control:{locked:true,constraint_source:'hail'},candidates:[{theta_by_asset_deg:[30],poa_front_effective_w_m2:100,admissible:true}]}]};assert.throws(()=>E.runCandidateSurface(pkg,{confirmMin:0}),/target CONTROL explícito/);});
const W=new Function(fs.readFileSync(root+'/overcast_workbench.js','utf8')+';return OvercastWorkbench;')();
test('CSV reports measured resolution in minutes',()=>assert.equal(W.parseCSV('timestamp,ghi,dni,dhi\n2026-01-01T00:00:00Z,300,0,300\n2026-01-01T00:01:00Z,310,0,310','test.csv').resolutionMin,1));
test('CSV rejects missing irradiance',()=>assert.throws(()=>W.parseCSV('timestamp,ghi,dni,dhi\n2026-01-01T00:00:00Z,,0,300\n2026-01-01T00:01:00Z,310,0,310','bad.csv'),/no válido/));
test('CSV rejects timestamps without a timezone',()=>assert.throws(()=>W.parseCSV('timestamp,ghi,dni,dhi\n2026-01-01T00:00:00,300,0,300\n2026-01-01T00:01:00Z,310,0,310','bad.csv'),/sin zona/));
test('P1 rejects duplicate asset identities',()=>assert.throws(()=>W.parseP1(JSON.stringify({schema:'overcast_p1_sequence_v1',timestamp:['2026-01-01T00:00:00Z'],asset_ids:['a','a'],operational:false})),/identidades/));
test('P1 v2 accepts a complete candidate surface',()=>{const p={schema:'overcast_p1_candidates_v2',operational:false,asset_ids:['a'],timestamp:['2026-01-01T00:00:00Z'],grid:{angle_resolution_deg:.1},provenance:{engine:'core'},steps:[{timestamp:'2026-01-01T00:00:00Z',baseline_candidate:0,candidates:[{theta_by_asset_deg:[1],poa_front_effective_w_m2:100,admissible:true}]}]};assert.equal(W.parseP1(JSON.stringify(p)).schema,'overcast_p1_candidates_v2');});
test('P1 v2 accepts explicit hard CONTROL and rejects ambiguous locked state',()=>{const p={schema:'overcast_p1_candidates_v2',operational:false,asset_ids:['a'],timestamp:['2026-01-01T00:00:00Z'],grid:{angle_resolution_deg:.1},provenance:{engine:'core'},steps:[{timestamp:'2026-01-01T00:00:00Z',baseline_candidate:0,cloud_cover_fraction:.9,control:{locked:true,constraint_source:'battery_low',target_by_asset_deg:[0]},candidates:[{theta_by_asset_deg:[1],poa_front_effective_w_m2:100,admissible:true}]}]};assert.equal(W.parseP1(JSON.stringify(p)).steps[0].control.constraint_source,'battery_low');delete p.steps[0].control.target_by_asset_deg;assert.throws(()=>W.parseP1(JSON.stringify(p)),/target\/fuente explícitos/);});
console.log('TODO OK — '+checks+' comprobaciones');
